import { chromium } from '@playwright/test'
const out = process.argv[2]
const browser = await chromium.launch()
const ctx = await browser.newContext({ storageState: 'e2e/.auth/owner.json', viewport: { width: 1440, height: 900 } })
const page = await ctx.newPage()
const errors = []
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
await page.goto('http://localhost:3000/tasks')
await page.getByRole('button', { name: /^New task$/ }).first().click()
const drawer = page.getByRole('dialog')
await drawer.waitFor()
console.log('focused:', await page.evaluate(() => document.activeElement?.tagName + ' ' + (document.activeElement?.getAttribute('placeholder') ?? '')))
await drawer.getByRole('button', { name: 'Create' }).click()
await page.waitForTimeout(300)
console.log('alert:', await drawer.getByRole('alert').textContent())
console.log('focused after:', await page.evaluate(() => document.activeElement?.tagName + ' ' + (document.activeElement?.getAttribute('aria-invalid') ?? '')))
await drawer.screenshot({ path: out })
await page.keyboard.press('Tab')
console.log('after tab:', await page.evaluate(() => document.activeElement?.getAttribute('aria-label') ?? document.activeElement?.tagName))
console.log('console errors:', errors)
await browser.close()
