import { describe, expect, it } from 'vitest'
import { getModules } from './modules'
import { renderIndex } from '../scripts/gen-index.mjs'

const modules = getModules()

describe('the module index', () => {
  it('is not empty, so a broken gen:index fails loudly here', () => {
    expect(modules.length).toBeGreaterThan(0)
  })

  it('gives every module a unique id', () => {
    const ids = modules.map((m) => m.id)
    expect(new Set(ids).size).toBe(ids.length)
  })

  // The id is the Postgres schema name and the URL segment, so it has to be a
  // bare lowercase identifier: no dashes, no quoting, no escaping.
  it('uses ids that are valid schema names and URL segments', () => {
    for (const m of modules) {
      expect(m.id, `module id ${m.id}`).toMatch(/^[a-z][a-z0-9_]*$/)
    }
  })

  // Tools are exposed over MCP as `<id>.<tool>`, which is parsed on the dot.
  it('uses tool names that are valid identifiers', () => {
    for (const m of modules) {
      for (const name of Object.keys(m.tools)) {
        expect(name, `${m.id}.${name}`).toMatch(/^[a-z][a-z0-9_]*$/)
      }
    }
  })

  it('gives every module the get_digest tool core depends on', () => {
    for (const m of modules) {
      expect(Object.keys(m.tools), `module ${m.id}`).toContain('get_digest')
    }
  })

  // Page keys are joined onto /<id>/, so a leading slash would double it.
  it('uses page keys with no leading slash', () => {
    for (const m of modules) {
      for (const key of Object.keys(m.pages)) {
        expect(key, `${m.id} page "${key}"`).not.toMatch(/^\//)
      }
    }
  })

  it('gives every module an index page', () => {
    for (const m of modules) {
      expect(Object.keys(m.pages), `module ${m.id}`).toContain('')
    }
  })

  it('only guards tools that exist', () => {
    for (const m of modules) {
      for (const tool of m.guarded ?? []) {
        expect(Object.keys(m.tools), `${m.id} guards ${tool}`).toContain(tool)
      }
    }
  })

  it('orders the nav with numbers', () => {
    for (const m of modules) {
      expect(typeof m.nav.order, `module ${m.id}`).toBe('number')
    }
  })

  it('gives every job a unique name within its module', () => {
    for (const m of modules) {
      const names = (m.jobs ?? []).map((j) => j.name)
      expect(new Set(names).size, `module ${m.id}`).toBe(names.length)
    }
  })
})

describe('renderIndex', () => {
  it('sorts entries so the output does not churn with directory order', () => {
    const shuffled = renderIndex('modules', ['tasks', 'finance', 'notes'])
    const sorted = renderIndex('modules', ['finance', 'notes', 'tasks'])
    expect(shuffled).toBe(sorted)
  })

  it('imports each manifest and exports them as one array', () => {
    const out = renderIndex('modules', ['notes', 'finance'])
    expect(out).toContain("import finance from './finance/manifest'")
    expect(out).toContain("import notes from './notes/manifest'")
    expect(out).toContain('export const modules = [finance, notes]')
  })

  it('marks the file as generated so nobody hand edits it', () => {
    expect(renderIndex('modules', ['notes'])).toMatch(/generated by/i)
  })

  it('produces a valid empty array when there are no folders yet', () => {
    expect(renderIndex('integrations', [])).toContain('export const integrations = []')
  })
})
