import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

// Writes modules/_index.ts and integrations/_index.ts by globbing for manifest
// files. Runs as predev, prebuild, and pretest, so adding a folder is the only
// step needed to register a module or an integration.

type Kind = 'modules' | 'integrations'

/** Pure so the determinism test does not need a filesystem. */
export function renderIndex(kind: Kind, names: string[]): string {
  const sorted = [...names].sort()
  const imports = sorted.map((n) => `import ${n} from './${n}/manifest'`).join('\n')
  return [
    `// Generated by scripts/gen-index.ts. Do not edit; run pnpm gen:index.`,
    imports,
    '',
    `export const ${kind} = [${sorted.join(', ')}]`,
    '',
  ]
    .filter((line, i) => !(i === 1 && line === ''))
    .join('\n')
}

function folders(kind: Kind): string[] {
  const root = join(process.cwd(), kind)
  if (!existsSync(root)) return []
  return readdirSync(root, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(root, e.name, 'manifest.ts')))
    .map((e) => e.name)
}

function write(kind: Kind): void {
  const names = folders(kind)
  // integrations/ does not exist until Step 7 adds one; the index still has to.
  mkdirSync(join(process.cwd(), kind), { recursive: true })
  writeFileSync(join(process.cwd(), kind, '_index.ts'), renderIndex(kind, names))
  console.log(`${kind}/_index.ts: ${names.length} ${names.length === 1 ? 'entry' : 'entries'}`)
}

// Only run the I/O when invoked as a script, so importing renderIndex is free.
if (process.argv[1]?.endsWith('gen-index.mts')) {
  write('modules')
  write('integrations')
}
